name: Trivy Docker Image Scan

on:
  workflow_call:
    inputs:
      image-name:
        description: "Nombre de la imagen Docker"
        required: true
        type: string
      image-tag:
        description: "Tag de la imagen Docker"
        required: true
        type: string
      severity:
        description: "Nivel de severidad a reportar"
        default: "CRITICAL,HIGH"
        required: false
        type: string
      output-format:
        description: "Formato de salida de Trivy (sarif, json, table)"
        default: "sarif"
        required: false
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ inputs.image-name }}:${{ inputs.image-tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ inputs.image-name }}:${{ inputs.image-tag }}'
          format: ${{ inputs.output-format }}
          output: 'trivy-results.${{ inputs.output-format }}'
          severity: ${{ inputs.severity }}
          exit-code: 0

      - name: Upload Trivy SARIF results to GitHub Security tab
        if: ${{ inputs.output-format == 'sarif' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Upload Trivy results as artifact
        if: ${{ inputs.output-format != 'sarif' }}
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.${{ inputs.output-format }}
