name: Trivy Docker Image Scan

on:
  workflow_call:
    inputs:
      image-name:
        description: "Nombre de la imagen Docker"
        required: true
        type: string
      image-tag:
        description: "Tag de la imagen Docker"
        required: true
        type: string
      severity:
        description: "Nivel de severidad a reportar"
        default: "CRITICAL,HIGH"
        required: false
        type: string
      output-format:
        description: "Formato de salida de Trivy (sarif, json, table)"
        default: "sarif"
        required: false
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Scan Docker Image, Secrets, and IaC with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ inputs.image-name }}:${{ inputs.image-tag }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Image Scan (SARIF)
        if: ${{ inputs.output-format == 'sarif' }}
        run: |
          trivy image --format template \
            --template "@/contrib/sarif.tpl" \
            --output trivy-results.sarif \
            --severity ${{ inputs.severity }} \
            ${{ inputs.image-name }}:${{ inputs.image-tag }}

      - name: Run Trivy Image Scan (JSON/TABLE)
        if: ${{ inputs.output-format != 'sarif' }}
        run: |
          trivy image --format ${{ inputs.output-format }} \
            --output trivy-results.${{ inputs.output-format }} \
            --severity ${{ inputs.severity }} \
            --dependency-tree \
            ${{ inputs.image-name }}:${{ inputs.image-tag }}

      - name: Upload SARIF to GitHub Security tab
        if: ${{ inputs.output-format == 'sarif' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy Report Artifact
        if: ${{ inputs.output-format != 'sarif' }}
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.${{ inputs.output-format }}

      - name: Trivy Secret Scanning
        run: |
          trivy fs --scanners secret --severity ${{ inputs.severity }} . > trivy-secrets.txt

      - name: Upload Secrets Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-secrets
          path: trivy-secrets.txt

      - name: Trivy IaC Misconfiguration Scan
        run: |
          trivy config --severity ${{ inputs.severity }} . > trivy-iac.txt

      - name: Upload IaC Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac
          path: trivy-iac.txt
